#!/bin/bash

# Ensure that argument was passed in
if [ "$1" == '' ]; then
  echo "Please pass in the name of the new Rails app as an argument."
  exit 1
fi

# Get name of Rails app as argument
APP=$1

# Create Rails app with PostgreSQL setup
echo "Creating Rails app with PostgreSQL..."
rails new "${APP}" --database=postgresql
cd "${APP}"

# Create Docker files
echo "Creating Dockerfile and docker-compose.yml..."

touch Dockerfile

cat <<EOF >> Dockerfile

FROM ruby:2.3.4
RUN apt-get update && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir -p /${APP}
WORKDIR /${APP}
ADD Gemfile /${APP}/Gemfile
ADD Gemfile.lock /${APP}/Gemfile.lock
RUN gem install bundler && bundle install
ADD . /${APP}

EOF

touch docker-compose.yml

cat <<EOF >> docker-compose.yml

version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/${APP}
    ports:
      - "3000:3000"
    depends_on:
      - db

EOF

echo "Done!"
